(() => {
  "use strict";
  const $ = (selector) => document.querySelector(selector);
  const form = $("#apartmentForm");
  const status = $("#formStatus");
  const list = $("#adminApartmentList");
  const previews = $("#imagePreviewList");
  const areaInput = $("#area");
  const filesInput = $("#imageFiles");
  const contentForm = $("#contentForm");
  const contentStatus = $("#contentStatus");
  const allTextEditors = $("#allTextEditors");
  let textOverrides = {};
  let csrfToken = "";
  let images = [];
  let nextCursor = null;
  let listing = [];

  function message(text = "", kind = "") { status.textContent = text; status.className = `status ${kind}`; }
  function contentMessage(text = "", kind = "") { contentStatus.textContent = text; contentStatus.className = `status ${kind}`; }
  function renderTextEditors(texts) { allTextEditors.replaceChildren(); texts.forEach((text) => { const label = document.createElement("label"); label.dataset.text = text; label.textContent = text; const input = document.createElement("textarea"); input.value = textOverrides[text] || text; input.oninput = () => { if (input.value.trim() === text) delete textOverrides[text]; else textOverrides[text] = input.value.trim(); }; label.append(input); allTextEditors.append(label); }); }
  async function loadContent() { const [{ content }, { texts }] = await Promise.all([api("/api/admin/content"), api("/api/admin/content/catalog")]); textOverrides = content.overrides || {}; $("#heroEyebrow").value = content.heroEyebrow; $("#heroTitle").value = content.heroTitle; $("#heroDescription").value = content.heroDescription; $("#contentConsultationTitle").value = content.consultationTitle; $("#contentConsultationDescription").value = content.consultationDescription; $("#contentAppTitle").value = content.appTitle; $("#contentAppDescription").value = content.appDescription; $("#contentPhone").value = content.contactPhone; $("#contentFooterText").value = content.footerText; renderTextEditors(texts); }
  function contentData() { return { heroEyebrow: $("#heroEyebrow").value, heroTitle: $("#heroTitle").value, heroDescription: $("#heroDescription").value, consultationTitle: $("#contentConsultationTitle").value, consultationDescription: $("#contentConsultationDescription").value, appTitle: $("#contentAppTitle").value, appDescription: $("#contentAppDescription").value, contactPhone: $("#contentPhone").value, footerText: $("#contentFooterText").value, overrides: textOverrides }; }
  function finishLabel(value) { return ({ super: "Super", super_deluxe: "Super Deluxe", vip: "VIP" })[value] || value; }
  function data() { return { title: $("#title").value, area: areaInput.value, finishType: $("#finishType").value, status: $("#status").value, price: $("#price").value, areaSqm: $("#areaSqm").value, floor: $("#floor").value, bedrooms: $("#bedrooms").value, bathrooms: $("#bathrooms").value, description: $("#description").value, images }; }
  async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { Accept: "application/json", ...(options.body ? { "Content-Type": "application/json", "X-CSRF-Token": csrfToken } : {}), ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "تعذر إكمال الطلب"); return payload; }
  function renderImages() { previews.replaceChildren(); images.forEach((image, index) => { const item = document.createElement("div"); item.className = "image-thumb"; const img = document.createElement("img"); img.src = image.url; img.alt = "صورة الشقة"; const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "×"; remove.onclick = () => { images.splice(index, 1); renderImages(); }; item.append(img, remove); previews.append(item); }); }
  function reset() { form.reset(); $("#apartmentId").value = ""; $("#formMode").textContent = "شقة جديدة"; $("#cancelEdit").hidden = true; images = []; renderImages(); message(); }
  function card(apartment) { const row = document.createElement("article"); row.className = "apartment-row"; const image = apartment.images?.[0]?.url ? document.createElement("img") : document.createElement("div"); image.className = apartment.images?.[0]?.url ? "" : "image-empty"; if (apartment.images?.[0]?.url) { image.src = apartment.images[0].url; image.alt = apartment.title; } else image.textContent = "بدون صورة"; const copy = document.createElement("div"); const title = document.createElement("h3"); title.textContent = apartment.title; const details = document.createElement("p"); details.textContent = `${apartment.area} · ${finishLabel(apartment.finishType)} · ${new Intl.NumberFormat("ar-JO").format(apartment.price)} د.أ`; const meta = document.createElement("small"); meta.textContent = `${apartment.bedrooms} غرف · ${apartment.areaSqm} م² · ${apartment.status === "published" ? "منشور" : "مسودة"}`; copy.append(title, details, meta); const actions = document.createElement("div"); actions.className = "row-actions"; const edit = document.createElement("button"); edit.textContent = "تعديل"; edit.onclick = () => editApartment(apartment); const remove = document.createElement("button"); remove.textContent = "حذف"; remove.onclick = () => removeApartment(apartment); actions.append(edit, remove); row.append(image, copy, actions); return row; }
  function renderList(items, append = false) { if (!append) list.replaceChildren(); items.forEach((item) => list.append(card(item))); if (!items.length && !append) list.textContent = "لا توجد شقق مطابقة."; }
  async function load(append = false) { const params = new URLSearchParams({ limit: "20" }); const area = $("#adminAreaFilter").value.trim(); const finish = $("#adminFinishFilter").value; if (area) params.set("area", area); if (finish) params.set("finish", finish); if (append && nextCursor) params.set("cursor", nextCursor); const result = await api(`/api/admin/apartments?${params}`); listing = append ? [...listing, ...result.items] : result.items; nextCursor = result.nextCursor; renderList(result.items, append); $("#loadMore").hidden = !nextCursor; }
  function editApartment(apartment) { $("#apartmentId").value = apartment.id; $("#formMode").textContent = "تعديل شقة"; $("#cancelEdit").hidden = false; $("#title").value = apartment.title; areaInput.value = apartment.area; $("#finishType").value = apartment.finishType; $("#status").value = apartment.status; $("#price").value = apartment.price; $("#areaSqm").value = apartment.areaSqm; $("#floor").value = apartment.floor ?? ""; $("#bedrooms").value = apartment.bedrooms; $("#bathrooms").value = apartment.bathrooms; $("#description").value = apartment.description || ""; images = apartment.images || []; renderImages(); form.scrollIntoView({ behavior: "smooth" }); }
  async function removeApartment(apartment) { if (!confirm(`حذف «${apartment.title}» نهائيًا؟`)) return; try { await api(`/api/admin/apartments/${apartment.id}`, { method: "DELETE", body: "{}" }); await load(); message("تم حذف الشقة.", "success"); } catch (error) { message(error.message, "error"); } }
  async function uploadFiles(files) { if (images.length + files.length > 12) throw new Error("الحد الأقصى 12 صورة."); for (const file of files) { if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 8 * 1024 * 1024) throw new Error("الصورة يجب أن تكون JPG أو PNG أو WebP وأقل من 8MB."); const signature = await api("/api/admin/cloudinary/signature", { method: "POST", body: "{}" }); const body = new FormData(); body.append("file", file); body.append("api_key", signature.apiKey); body.append("timestamp", signature.timestamp); body.append("folder", signature.folder); body.append("signature", signature.signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/image/upload`, { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "تعذر رفع الصورة"); images.push({ url: result.secure_url, publicId: result.public_id }); renderImages(); } }
  async function initialize() { try { const [session, site] = await Promise.all([api("/api/auth/session"), api("/api/site-config")]); csrfToken = session.csrfToken; if (site.publicOrigin) $("#publicHomeLink").href = site.publicOrigin; if (!session.user || session.user.role !== "admin") { $("#accessNotice").hidden = false; $("#accessMessage").textContent = session.user ? "حسابك مسجّل لكنه ليس ضمن ADMIN_EMAILS." : "سجّل الدخول بحساب أدمن ثم أعد فتح هذه الصفحة."; return; } $("#adminWorkspace").hidden = false; $("#adminAccount").textContent = `أدمن: ${session.user.name}`; await Promise.all([load(), loadContent()]); } catch (error) { $("#accessNotice").hidden = false; $("#accessMessage").textContent = error.message; } }
  areaInput.addEventListener("input", async () => { const q = areaInput.value.trim(); if (q.length < 2) return; try { const { areas } = await api(`/api/areas?q=${encodeURIComponent(q)}`); const options = $("#areaSuggestions"); options.replaceChildren(); areas.forEach((name) => { const option = document.createElement("option"); option.value = name; options.append(option); }); } catch {} });
  filesInput.addEventListener("change", async () => { try { message("جارٍ رفع الصور…"); await uploadFiles([...filesInput.files]); message("تم رفع الصور.", "success"); } catch (error) { message(error.message, "error"); } finally { filesInput.value = ""; } });
  form.addEventListener("submit", async (event) => { event.preventDefault(); if (!form.reportValidity()) return; const id = $("#apartmentId").value; const button = $("#saveApartment"); button.disabled = true; message("جارٍ الحفظ…"); try { await api(id ? `/api/admin/apartments/${id}` : "/api/admin/apartments", { method: id ? "PUT" : "POST", body: JSON.stringify(data()) }); reset(); await load(); message("تم حفظ الشقة بنجاح.", "success"); } catch (error) { message(error.message, "error"); } finally { button.disabled = false; } });
  contentForm.addEventListener("submit", async (event) => { event.preventDefault(); if (!contentForm.reportValidity()) return; const button = contentForm.querySelector("button"); button.disabled = true; contentMessage("جارٍ الحفظ…"); try { await api("/api/admin/content", { method: "PUT", body: JSON.stringify(contentData()) }); contentMessage("تم تحديث موقع الزوار. حدّث صفحة الموقع لرؤية التغيير.", "success"); } catch (error) { contentMessage(error.message, "error"); } finally { button.disabled = false; } });
  $("#contentTextSearch").addEventListener("input", (event) => { const q = event.target.value.trim(); allTextEditors.querySelectorAll("label").forEach((label) => { label.hidden = Boolean(q && !label.dataset.text.includes(q)); }); });
  $("#newApartment").onclick = reset; $("#cancelEdit").onclick = reset; $("#loadMore").onclick = () => load(true); $("#adminAreaFilter").oninput = () => load(); $("#adminFinishFilter").onchange = () => load(); initialize();
})();
